<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-16 at 23:40:12.
 * $Id: DbOpTest.php,v c38e4da2bea6 2016/03/03 12:15:49 makhtar $
 */
class DbOpTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DbOp
     */
    protected $db;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->db = new DbOp;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DbOp::Connect
     * @todo   Implement testConnect().
     */
    public function testConnect() {
        $con = $this->db->Connect();
        print_r($con);
      //  $this->assertInstanceOf(PDO::class, $con);
    }

    /**
     * @covers DbOp::Query
     * 
     */
    public function testQuery() {
        $result = $this->db->Query("SELECT * from " . TB_CONTACT . " LIMIT 1");
        print_r($result);
        $row = $result->fetch();
        print_r($row);
        $this->assertNotEmpty($row);
        $this->assertArrayHasKey('name', $row);
    }

    /**
     * @covers DbOp::Execute
     *
     */
    public function testExecute() {
        $result = $this->db->PrepExecute("SELECT * from " . TB_CONTACT . " LIMIT 1");
        print_r($result);
        $row = $result->fetch();
        print_r($row);
        $this->assertNotEmpty($row);
        $this->assertArrayHasKey('first_name', $row);
    }

}
